### PR TITLE
Fix and cleanup the Android buildscripts

### LINKED ISSUE #9: [Android build] Abort on errors make all scripts to fail
Someone put thoses lines on every files related to Android building:
```
# abort on errors
set -e
```

It breaks all the building script : if just one line return a non success code, it ends. A lot of line return a non success code if the script is used a second time.

### PR DESCRIPTION
**Pull request by carstene1ns**
Fixes #9.
Also saves some time.

### CODE REVIEW

File: android/2_build_toolchain.sh [hunk 1]
```diff
@@ -139,17 +123,19 @@ function install_lib_sdl {
...
 
 # Install SDL2_mixer
 function install_lib_mixer() {
 	cd SDL_mixer
-	./configure --host=$TARGET_HOST --prefix=$PLATFORM_PREFIX --disable-sdltest \
-		--enable-music-mp3-mad-gpl --disable-music-mp3-smpeg \
-		--disable-shared --enable-static
+	SDL_CFLAGS="-I $PLATFORM_PREFIX/include/SDL2" SDL_LIBS="-lSDL2" \
+		./configure --host=$TARGET_HOST --prefix=$PLATFORM_PREFIX --disable-shared --enable-static \
+		--disable-sdltest --disable-music-mp3 \
```
Comment (carstene1ns) [inline android/2_build_toolchain.sh]: whoops, stray blackslash

**Comment by carstene1ns** [comment]
Downloading takes now 5m29s and a full ccache enabled rebuild 25m45s on server.
That being said, the current toolchain is already using this.

File: android/2_build_toolchain.sh [hunk 2]
```diff
@@ -181,17 +112,17 @@ export PKG_CONFIG_PATH=$PLATFORM_PREFIX/lib/pkgconfig
...
-install_lib_vorbis
-install_lib_modplug
+install_lib libpng-1.6.23
+install_lib freetype-2.6.3 --with-harfbuzz=no --without-bzip2
+install_lib pixman-0.34.0
+install_lib libogg-1.3.2
+install_lib libvorbis-1.3.5
+install_lib libmodplug-0.8.8.5
+install_lib libsndfile-1.0.27
+install_lib speexdsp-1.2rc3 --enable-sse --disable-neon
```
Comment (Ghabry) [inline android/2_build_toolchain.sh]: Uh thats cool didnt knew you can pass args this way withou "" and then just using $@

Comment (carstene1ns) [inline android/2_build_toolchain.sh]: The key is using `shift` here to remove the first argument.

File: android/1_download_library.sh [hunk 3]
```diff
@@ -124,13 +141,17 @@ download_and_extract http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.27
...
+mkdir -p SDL
+extract SDL.tar.gz --strip-components=1 -C SDL
 
-msg "Cloning SDL2_mixer"
+# SDL_mixer
 rm -rf SDL_mixer/
-hg clone http://hg.libsdl.org/SDL_mixer
+download https://hg.libsdl.org/SDL_mixer/archive/tip.tar.gz -O SDL_mixer.tar.gz --no-timestamping
+mkdir -p SDL_mixer
+extract SDL_mixer.tar.gz --strip-components=1 -C SDL_mixer
```
Comment (Ghabry) [inline android/1_download_library.sh]: Iirc the only reason to use mercurial was because we needed a version after 2.0.3 but 2.0.4 wasnt out yet and then nobidy ever updated the script to pick 2.0.4
Keep it this way or change it?  Based on the incredible dev speed of sdl probably makes no difference

Comment (carstene1ns) [inline android/1_download_library.sh]: heh, yes could be changed then. Maybe sometime there will get incompatible changes merged in, then we are safe, but I guess we will need to use this again when there is no sdl release the next 2 years :ghost:.

Comment (Ghabry) [inline android/1_download_library.sh]: seems legit
